### ISSUE TITLE
Multiple Targets in PDAO

### ISSUE THREAD

**Issue by inesrob** [roll-wg/dao-projection#13]
Source: https://mailarchive.ietf.org/arch/msg/roll/2enaFoWTT-yXe-31r-6xE3MfEtA/

Dear all: we had this thread as part of Li's review:

About : "5.1 One and only one RPL Target Option MUST be present in the message."

[Li] -> Is it possible to remove the limitation?  It's not flexible If PDR can only carry one RTO.
            For instance in figure 7, if node I requests P-Route to B&H together, Root can only push one Track I->A->B->H. Otherwise, Root may push two Tracks I->A->B and I->F->G->H.
             If Root cannot computer one Track to multiple RTO, it can response with a special PDR-ACK Status.

[PT]  This was done in the interest to simplicity, and yes we can rediscuss that.
We'd need to make decisions on partially successful use cases e.g.,:

  *   What if there's a path to only a subset? Should the root form more than one track?
  *   Or deny with your special status but then what can the source do after that? Try all combinations?
  *   What is the best path to one target cannot reach all targets but a lower quality path can? Should we use that one?
  *   Maybe there could be one main target and additional desirable targets? In that case the Root could form the track and indicate which of the optional targets are effectively reachable via the track to the main target.

[Li] Maybe it depends on implement of PCE?  I'd like to keep the flexibility because there is a user case for street lighting. Some controllers(Ingress nodes) need to light the street lighting linearly with low-latency.

[PT] sure, at the expense of complexity in signaling and processing in the nodes. We need to  be specific on the scenarios and status codes. The PDR forms a single Track since the TrackID is provided.

I believe it makes sense to ask for more targets since the root can install a Track for more than one target. Still,  signaling is involved and we need a story for all those questions:

  *   What if there's a path to only a subset? Should the root form more than one track?
  *   Or deny with your special status but then what can the source do after that? Try all combinations?
  *   What is the best path to one target cannot reach all targets but a lower quality path can? Should we use that one?
  *   Maybe there could be one main target and additional desirable targets? In that case the Root could form the track and indicate which of the optional targets are effectively reachable via the track to the main target.

Comments welcome!

Pascal

**Comment by pthubert** [comment]
[From:]() Li Zhao (liz3) <liz3@cisco.com> 
Sent: jeudi 24 février 2022 9:38
To: Pascal Thubert (pthubert) <[pthubert@cisco.com](mailto:pthubert@cisco.com)>; ROLL WG ([roll@ietf.org](mailto:roll@ietf.org)) <[roll@ietf.org](mailto:roll@ietf.org)>
Subject: Re: Multiple targets in PDR (Was: [Roll] review of dao-projection -22)

Hello Pascal,

The new proposal looks good to me.
In most cases, we can use one Target Option. Meanwhile allowing multiple targets keeps the possibility of extension in future.


Best regards,
Li

From: Pascal Thubert (pthubert) <pthubert@cisco.com>
Date: Tuesday, February 22, 2022 at 22:55
To: ROLL WG (roll@ietf.org) <roll@ietf.org>
Cc: Li Zhao (liz3) <[liz3@cisco.com](mailto:liz3@cisco.com)>
Subject: RE: Multiple targets in PDR (Was: [Roll] review of dao-projection -22)
Dear all:
 
To address Li’s comment, is we allow multiple targets then there can be a set of possible Track each leading to a subset of the listed Targets, and possibly not all or all with a very bad quality / PDR.
Suggestion is to accept more than one target, but focus the response on the first target and the “best” subset of the others the root can find.
IMHO, going into the details of the path quality or which subset is best takes us deeper than we can go in this draft.
 
So I suggest:
 
OLD
  
   One and only one RPL Target Option MUST be present in the message
 
New
 
   At least one RPL Target Option MUST be present in the message. If more than
   one RPL Target Option is present, the Root will provide a Track that reaches
   the first listed Target and a subset of the other Target; details of the
   subset selection are out of scope.
 
Works?
 
Pascal
 
From: Pascal Thubert (pthubert) 
Sent: vendredi 14 janvier 2022 10:20
To: ROLL WG ([roll@ietf.org](mailto:roll@ietf.org)) <[roll@ietf.org](mailto:roll@ietf.org)>
Cc: Li Zhao (liz3) <[liz3@cisco.com](mailto:liz3@cisco.com)>
Subject: Multiple targets in PDR (Was: [Roll] review of dao-projection -22)
 
Dear all: we had this thread as part of Li’s review:
 
About : “5.1 One and only one RPL Target Option MUST be present in the message.”
 
[Li] -> Is it possible to remove the limitation?  It’s not flexible If PDR can only carry one RTO.
            For instance in figure 7, if node I requests P-Route to B&H together, Root can only push one Track I->A->B->H. Otherwise, Root may push two Tracks I->A->B and I->F->G->H.
             If Root cannot computer one Track to multiple RTO, it can response with a special PDR-ACK Status.
 
[PT]  This was done in the interest to simplicity, and yes we can rediscuss that. 
We’d need to make decisions on partially successful use cases e.g.,:
•	What if there’s a path to only a subset? Should the root form more than one track? 
•	Or deny with your special status but then what can the source do after that? Try all combinations?
•	What is the best path to one target cannot reach all targets but a lower quality path can? Should we use that one?
•	Maybe there could be one main target and additional desirable targets? In that case the Root could form the track and indicate which of the optional targets are effectively reachable via the track to the main target.
 
[Li] Maybe it depends on implement of PCE?  I’d like to keep the flexibility because there is a user case for street lighting. Some controllers(Ingress nodes) need to light the street lighting linearly with low-latency.
 
[PT] sure, at the expense of complexity in signaling and processing in the nodes. We need to  be specific on the scenarios and status codes. The PDR forms a single Track since the TrackID is provided.
 
 
I believe it makes sense to ask for more targets since the root can install a Track for more than one target. Still,  signaling is involved and we need a story for all those questions:
•	What if there’s a path to only a subset? Should the root form more than one track? 
•	Or deny with your special status but then what can the source do after that? Try all combinations?
•	What is the best path to one target cannot reach all targets but a lower quality path can? Should we use that one?
•	Maybe there could be one main target and additional desirable targets? In that case the Root could form the track and indicate which of the optional targets are effectively reachable via the track to the main target.
 
Comments welcome!
 
Pascal
